In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [3]:
df = pd.read_csv(r'C:\Users\sai\Desktop/heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [6]:
endog = df['target'].head(4)


In [7]:
exog =  df[['slope','sex','age']].head(4)

In [8]:
print(exog)

   slope  sex  age
0      0    1   63
1      0    1   37
2      2    0   41
3      2    1   56


In [9]:
X=exog.to_numpy()

In [10]:
Y= endog.to_numpy()

In [11]:
print(X)

[[ 0  1 63]
 [ 0  1 37]
 [ 2  0 41]
 [ 2  1 56]]


In [12]:
from numpy import array
from numpy import mean

In [13]:
from numpy import cov
from numpy.linalg import eig

In [14]:
M = mean(X.T, axis=1)

In [15]:
print(M)

[ 1.    0.75 49.25]


In [16]:
C= X-M

In [17]:
print(C)

[[ -1.     0.25  13.75]
 [ -1.     0.25 -12.25]
 [  1.    -0.75  -8.25]
 [  1.     0.25   6.75]]


In [18]:
V = cov(C.T)

In [19]:
print(V)

[[  1.33333333  -0.33333333  -1.        ]
 [ -0.33333333   0.25         2.75      ]
 [ -1.           2.75       150.91666667]]


In [20]:
values, vectors = eig(V)

In [21]:
print(vectors)

[[-0.0067221   0.96765856 -0.252174  ]
 [ 0.01825673 -0.2520189  -0.96755008]
 [ 0.99981073  0.01110784  0.01597219]]


In [22]:
print(values)

[1.50973606e+02 1.40866824e+00 1.17726215e-01]


In [23]:
P = vectors.T.dot(C.T)

In [24]:
print(P.T)

[[ 13.75868388  -0.87793052   0.22990404]
 [-12.23639522  -1.16673429  -0.1853728 ]
 [ -8.26885321   1.06503308   0.34171803]
 [  6.74656455   0.97963174  -0.38624926]]


In [25]:
from sklearn.decomposition import PCA

In [26]:
pca = PCA(n_components=1)

In [27]:
principalComponents = pca.fit_transform(X)

In [28]:
principalDf = pd.DataFrame(data = principalComponents,columns = ['principal component 1'])

In [29]:
exog1 = sm.add_constant(principalDf[['principal component 1']])

In [30]:
print(exog1)

   const  principal component 1
0    1.0              13.758684
1    1.0             -12.236395
2    1.0              -8.268853
3    1.0               6.746565


In [31]:
from sklearn import linear_model

In [32]:
lm = linear_model.LinearRegression()

In [33]:
model = lm.fit(exog1,endog)

In [34]:
lm.coef_

array([0., 0.])

In [35]:
lm.intercept_

1.0

In [42]:
def RSE(y_true, y_predicted):
    
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))
    rse = math.sqrt(RSS / (len(y_true) - 2))
    return rse

In [43]:
ypred =lm.predict(exog1)

In [44]:
re = RSE(endog,ypred)
print(re)

0.0
